import "./globals.css";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { config } from "@/config";
import Web3ModalProvider from "@/context";
import StoreProvider from "@/redux/StoreProvider";
import ClientWrapper from "./ClientWrapper";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Main({ children }) {
  const initialState = getInitialState();
  

  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <Web3ModalProvider initialState={initialState}>
            <ClientWrapper />
            {children}
          </Web3ModalProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
async function getInitialState() {
  const headersData = headers(); // Get the headers (async)
  const cookie = headersData.get("cookie"); // Get the cookie value
  return cookieToInitialState(config, cookie); // Process and return initial state
}
